apps/recipes/urls.py
#from django
from django.conf.urls.defaults import *

# from recipes
from recipes.models import Recipe

urlpatterns = patterns('',
        url(r'^$', 'recipes.views.recipes', name="recipes"),
                 url(r'^searchrecipes/$', 'recipes.views.searchrecipes', name="searchrecipes"),
        url(r'^(\d+)/recipe/$', 'recipes.views.recipe', name="describe_recipe"),
        url(r'^your_recipes/$', 'recipes.views.your_recipes', name="your_recipes"),
        url(r'^myrecipes/(?P<user_name>[\w\._-]+)/$', 'recipes.views.myrecipes', name="myrecipes"),
        # CRUD urls
        url(r'^upload/$', 'recipes.views.upload_recipe', name="upload_recipe"),
        url(r'^(\d+)/update/$', 'recipes.views.update_recipe', name="update_recipe"),
         url(r'^(\d+)/updateimg/$', 'recipes.views.update_recipeimg', name="update_recipeimg"),
        url(r'^(\d+)/delete/$', 'recipes.views.delete_recipe', name="delete_recipe"),
        url(r'^favourite/(?P<recipe_id>\w+)/(?P<user_name>[\w\._-]+)/$', 'recipes.views.favourite_recipe', name="favourite_recipe"),
        url(r'^favremove/(?P<recipe_id>\w+)/(?P<user_name>[\w\._-]+)/$','recipes.views.favremove_recipe', name="favremove_recipe"),
        url(r'^raterecipe/(?P<recipe_id>\w+)/(?P<user_name>[\w\._-]+)/(?P<rating>\w+)/$', 'recipes.views.raterecipe', name="raterecipe"), 
        url(r'^(\d+)/rate_recipe/$','recipes.views.rate_recipe', name="rate_recipe"),   
        url(r'^suggest/(?P<recipe_category>\w+)/$','recipes.views.suggest_recipes', name="suggest_recipes"),
        url(r'^viewsugrecipes/(?P<user>[\w\._-]+)/$','recipes.views.viewsugrecipes', name="viewsugrecipes"),  
        url(r'^selectcategory/$','recipes.views.select_sug_recipes', name="select_sug_recipes"),   
        url(r'^profiledisp_data/(?P<other_user>[\w\._-]+)/$', 'recipes.views.profiledisp_data', name="profiledisp_data"),
        url(r'^recipeshuffle/$', 'recipes.views.recipeshuffle', name="recipeshuffle"),
        url(r'^trendingrecipes/$', 'recipes.views.trendingrecipes', name="trendingrecipes"),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

from pinax.apps.account.openid_consumer import PinaxConsumer


handler500 = "pinax.views.server_error"


urlpatterns = patterns("",
  #  url(r"^$", direct_to_template, {
   #     "template": "landing.html",
    #}, name="home"),
    url(r"^$",'views.homeview',name="home"),
    url(r"^admin/invite_user/$", "pinax.apps.signup_codes.views.admin_invite_user", name="admin_invite_user"),
    url(r"^frienddecline/(?P<invitation_id>)/(?P<user_name>\w+)/$", "apps.friends.views.frienddecline", name="frienddecline"), 
    url(r"^friendaccept/(?P<invitation_id>)/(?P<user_name>\w+)/$", "apps.friends.views.friendaccept", name="friendaccept"), 
    url(r'', include('social_auth.urls')),

    url(r"^admin/", include(admin.site.urls)),
    url(r"^about/", include("apps.about.urls")),
    url(r"^account/", include("apps.account.urls")),
    url(r"^openid/", include(PinaxConsumer().urls)),
    url(r"^profiles/", include("profiles.urls")),
    url(r"^box/", include("notification.urls")),
    url(r"^announcements/", include("announcements.urls")),
    url(r"^displaypic/", include("apps.avatar.urls")),
    url(r"^friends/", include("friends.urls")),
    url(r"^messages/", include("messages.urls")),
    url(r"^comments/", include("threadedcomments.urls")),
    url(r"^i18n/", include("django.conf.urls.i18n")),
    url(r"^photos/", include("photos.urls")),
    url(r"^displaypic/", include("avatar.urls")),
    url(r"^flag/", include("flag.urls")),
    url(r"^recipes/",include("recipes.urls")),
    url(r"^restaurants/",include("restaurants.urls")),
    url(r"^socialstream/",include("socialstream.urls")),
    url(r"^search/", include("haystack.urls")),
)


#if settings.SERVE_MEDIA:
 #   urlpatterns += patterns("",
  #      url(r"", include("staticfiles.urls")),
   #     (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),
    #)

apps/recipes/models.py
# python
import os
from os import path
from datetime import datetime

# django imports
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from profiles.models import Profile




#from djangoratings
from djangoratings.fields import RatingField


class Recipe(models.Model):
    """
    Recipe Model: name, alsoknownas, category, preparation, recipeart, adder,     added,recipetype,mostlycookedin,energylevels,health,ingredients,video,userfav,taste,cookingtime,description
      """
    RECIPETYPE_CHOICES = (
           ('Vegetarian','Vegetarian'),
           ('Non-Vegetarian','Non-Vegetarian'),
     ) 
    TASTE_CHOICES = (
           ('Spicy','Spicy'),
           ('Sweet','Sweet'),
           ('Mild','Mild'),
           ('Sour','Sour'),
           ('SweetSour','Sweet & Sour'),
           ('Tangy','Tangy'), 
    ) 
   
    MEAL_CHOICES = (
           ('Breakfast','Breakfast'),
           ('Lunch','Lunch'),
           ('Snack','Snack'),
           ('Dinner','Dinner'),
           ('Any Time','Any Time'), 
    ) 
    CATEGORY_CHOICES = (
           ('Beverages','Beverages'),
           ('Breads','Breads,Cakes'),
           ('Choco','Candy,Cookies,Chocolates'),
           ('SideDishes','Curries,Side-Dishes,Pickles,Chutneys'),
           ('DessertsSweets','Desserts & Sweets'),
           ('MainDishes','Main-Dishes,Rice'),
           ('Noodles','Noodles & Pastas'), 
           ('Salads','Salads'),
           ('Sandwiches','Pie,Pizza,Sandwiches'),
           ('Sauces','Sauces'),
           ('Snacks','Snacks'), 
           ('Soups','Soups'),
           ('Other','Other'),
    )
    COOKINGMETHOD_CHOICES = (
           ('Bake','Bake'),
           ('Blender','Blender'),
           ('Bread Machine','Bread Machine'),
           ('Broil','Broil'),
           ('Convection Oven','Convection Oven'),
           ('Fondue','Fondue'),
           ('Food Processor','Food Processor'), 
           ('Fry','Fry'),
           ('Grill','Grill'),
           ('Grill Pan','Grill Pan'),
           ('Grind','Grind'),
           ('Ice-Cream Maker','Ice-Cream Maker'), 
           ('Marinate','Marinate'),
           ('Microwave','Microwave'),
           ('Poach','Poach'),
           ('Pressure Cooker','Pressure Cooker'),
           ('Roast','Roast'),
           ('Microwave','Microwave'),
           ('Sandwich Press','Sandwich Press'),
           ('Slow Cook','Slow Cook'),
           ('Steam','Steam'),
           ('Waffle Maker','Waffle Maker'),
           
    )
    SERVINGS_CHOICES = (
           ('One','One'),
           ('Two','Two'),
           ('Three','Three'),
           ('Four','Four'),
           ('Five','Five'),
           ('Six','Six'),
           ('Seven','Seven'), 
           ('Eight','Eight'),
           ('Nine','Nine'),
           ('Ten','Ten'),
    )
    CUISINE_CHOICES = (
           ('African','African'),
           ('American','American'),
          
           ('Asian','Asian'),
           ('Austrian','Austrian'),
           ('Authentic','Authentic'),
           
           ('British','British'),
           ('Caribbean','Caribbean'),
            ('Chinese','Chinese'),
           ('Cuban','Cuban'),
           ('Eastern European','Eastern European'),
           ('French','French'),
           ('German','German'),
             ('Greek','Greek'),
             ('Hawaiian','Hawaiian'),
             ('Hungarian','Hungarian'),
            ('Andhra','Indian - Andhra'),
             ('Awadhi','Indian - Awadhi'),
           ('Bengali','Indian - Bengali'),
           ('Bihari','Indian - Bihari'),
            ('Goan','Indian - Goan'),
           ('Gujarati','Indian - Gujarati'), 
            ('Hyderabadi','Indian - Hyderabadi'),
           ('Jain','Indian - Jain'),
           ('Kashmiri','Indian - Kashmiri'),
           ('Maharashtrian','Indian - Maharashtrian'),
           ('Parsi','Indian - Parsi'),
           ('Punjabi','Indian - Punjabi'),
           ('Rajasthani','Indian - Rajasthani'),
           ('Sindhi','Indian - Sindhi'),
           ('South Indian','Indian - South Indian'),
            ('Italian','Italian'),
           ('Japanese','Japanese'),
            ('Jewish','Jewish'),
           ('Korean','Korean'),
            ('Malaysian','Malaysian'),
            ('Mediterranean','Mediterranean'),
             ('Mexican','Mexican'),
              ('Middle Eastern','Middle Eastern'),
             ('Moroccan','Moroccan'),
             ('Pacific Northwest','Pacific Northwest'),
             ('Scandinavian','Scandinavian'),
             ('South American','South American'), 
             ('Spanish','Spanish'),
             ('Swiss','Swiss'),
              ('Thai','Thai'), 
              ('Vietnamese','Vietnamese'),
            
     
     )
    COOKINGTIME_CHOICES = (
           ('0 to 5 Min','0 to 5 Minutes'),
           ('5 to 10 Min','5 to 10 Minutes'),
           ('10 to 15 Min','10 to 15 Minutes'),
           ('15 to 30 Min','15 to 30 Minutes'),
           ('30 Min to 1 Hour','30 Min to 1 Hour'),
           ('More than 1 Hr','More than 1 Hour'),
    )
    PREPARATION_CHOICES = (
           ('5 to 10 Min','5 to 10 Minutes'),
           ('10 to 15 Min','10 to 15 Minutes'),
           ('15 to 30 Min','15 to 30 Minutes'),
           ('30 Min to 1 Hour','30 Min to 1 Hour'),
           ('More than 1 Hr','More than 1 Hour'),
           ('More than 3 Hrs','More than 3 Hrs'),
           ('6 to 8 Hrs','6 to 8 Hours'),
           ('Half Day','Half Day'),
           ('1 Dy','1 Day'), 
           ('More than 1 Dy','More than 1 Day'),
           ('3 to 4 Days','3 to 4 Days'),
           ('A Week','A Week'),
    )
    name = models.CharField(_('Name'), max_length=255)
    alsoknownas = models.CharField(_('Also Known As'), max_length=255)
    category = models.CharField(_('Category'), max_length=255,null=False,choices=CATEGORY_CHOICES,default="Beverages")
    cuisine = models.CharField(_('Cuisine'), max_length=255,choices = CUISINE_CHOICES,default="Hyderabadi")
    preparation = models.TextField(_('Preparation'), blank=True)
    recipeart = models.ImageField(_('Recipe Art'),upload_to="recipes", blank=True, null=True) 
    recipetype = models.CharField(_('Recipe Type'), max_length=255,choices=RECIPETYPE_CHOICES,default="Vegetarian")
    mostlycookedin = models.CharField(_('Mostly Cooked In'), max_length=255)
    energylevels = models.CharField(_('energylevels'), max_length=255)
    taste = models.CharField(_('Taste'), max_length=255,choices=TASTE_CHOICES,default="Spicy")
    preferredat = models.CharField(_('Preferred At'), max_length=255,choices=MEAL_CHOICES,default="Lunch")
    ingredients = models.TextField(_('Ingredients'), blank=False)
    video = models.URLField(_('Video'), max_length=255, blank=True)
    calories = models.CharField(_('Calories'), max_length=255)
    preparationtime = models.CharField(_('Preparation Time'), max_length=255,choices = PREPARATION_CHOICES,default="5 to 10 Min")
    cookingtime = models.CharField(_('Cooking Time'), max_length=255,choices = COOKINGTIME_CHOICES,default="0 to 5 Min")
    cookingmethod = models.CharField(_('Cooking Method'), max_length=255,choices=COOKINGMETHOD_CHOICES,default="Bake")
    servings = models.CharField(_('Servings '), max_length=255,choices=SERVINGS_CHOICES,default="One")
    description = models.TextField(_('Description'),blank=True)
    
    rating = RatingField(range=5,can_change_vote = True) # 5 possible rating values, 1-5
    adder = models.ForeignKey(User, related_name="added_recipes", verbose_name=_('adder'))
    added = models.DateTimeField(_('added'), default=datetime.now)

    def get_absolute_url(self):
        return ("describe_recipe", [self.pk])
    get_absolute_url = models.permalink(get_absolute_url)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ('-added', )
        
    def _get_thumb_url(self, folder, size):
        """ get a thumbnail giver a folder and a size. """
        if not self.recipeart:
            return '#'       
        upload_to = path.dirname(self.recipeart.path)
        tiny = path.join(upload_to, folder, path.basename(self.recipeart.path))
        tiny = path.normpath(tiny)
        if not path.exists(tiny):
            import Image
            im = Image.open(self.recipeart.path)
            im.thumbnail(size, Image.ANTIALIAS)
            im.save(tiny, 'JPEG')  
        return path.join(path.dirname(self.recipeart.url), folder, path.basename(self.recipeart.path)).replace('\\', '/')

    def get_thumb_url(self):
        return self._get_thumb_url('thumb_400_400', (400,400))

    def get_thumbmedium_url(self):
        return self._get_thumb_url('thumb_100_100', (100,100))
    
    def thumb(self):
        """ Get thumb <a>. """
        link = self.get_thumb_url()
        if link is None:
            return '<a href="#" target="_blank">NO IMAGE</a>'
        else:
            return '<img src=%s />' % (link)
    thumb.allow_tags = True 
    
    def thumbmedium(self):
        """Get medium size thumb to display during fav,suggested and uploaded recipes"""
        link = self.get_thumbmedium_url()
        if link is None:
            return '<a href="#" target="_blank">NO IMAGE</a>'
        else:
            return '<img src=%s />' % (link)
    thumbmedium.allow_tags = True 
         
    def fullpicture(self):
        """ Get full picture <a>. """
        link = "%s%s" % (settings.MEDIA_URL, self.recipeart)
        if link is None:
            return '<a href="#" target="_blank">NO IMAGE</a>'
        else:
            return '<img src=%s />' % (link)
    thumb.allow_tags = True
    
    __original_image = None
 
    def __init__(self, *args, **kwargs):
        super(Recipe, self).__init__(*args, **kwargs)
        self.__original_image = self.recipeart
   
    def save(self, force_insert=False, force_update=False):
        if self.recipeart != self.__original_image and self.__original_image != '':

apps/recipes/forms.py
#from django
from django import forms
from django.utils.translation import ugettext_lazy as _

#from recipes
from recipes.models import Recipe
from django import forms
from django.utils.safestring import mark_safe

from recipes import admin

class RecipeForm(forms.ModelForm):
    """
    Recipe Form: form associated to the Recipe model
    """


    def __init__(self, *args, **kwargs):
        super(RecipeForm, self).__init__(*args, **kwargs)
        self.is_update = False
    
    def clean(self):
        """ Do validation stuff. """
        # name is mandatory
        if 'name' not in self.cleaned_data:
            return
        # if a recipe with that title already exists...
        if not self.is_update:
            if Recipe.objects.filter(name=self.cleaned_data['name']).count() > 0:
                raise forms.ValidationError(_("There is already this recipe in the database"))
        return self.cleaned_data
    
    class Meta:
        model = Recipe
        fields = ('recipeart','name', 'alsoknownas', 'recipetype','category', 'cuisine','cookingmethod','servings','ingredients','preparation', 'calories', 'mostlycookedin','taste','preferredat','video','cookingtime','preparationtime','description')

class RecipeEditForm(forms.ModelForm):
    """
    Recipe Edit Form: form associated to the Recipe model
    """
  

    def __init__(self, *args, **kwargs):
        super(RecipeEditForm, self).__init__(*args, **kwargs)
        self.is_update = False
    
    def clean(self):
        """ Do validation stuff. """
        # name is mandatory
        if 'name' not in self.cleaned_data:
            return
        # if a recipe with that title already exists...
        if not self.is_update:
            if Recipe.objects.filter(name=self.cleaned_data['name']).count() > 0:
                raise forms.ValidationError(_("There is already this recipe in the database"))
        return self.cleaned_data
    
    class Meta:
        model = Recipe
        fields = ('recipeart','name', 'alsoknownas', 'recipetype','category', 'cuisine','cookingmethod','servings','ingredients','preparation', 'calories', 'mostlycookedin','taste','preferredat','video','cookingtime','preparationtime','description')
        

apps/recipes/templates/recipes/previous_fav_recipe.html
{% extends "recipes/base.html" %}

{% load i18n %}

{% block head_title %}{% blocktrans %}Suggest Recipes{% endblocktrans %}{% endblock %}

{% block body %}
    <h1> Suggest Recipes based on your favorite recipes</h1>
{%endblock %}
    

apps/recipes/templates/recipes/recipes (copy).html
{% extends "recipes/recipes_base.html" %}

{% load i18n %}
{% load avatar_tags %}
{% load pagination_tags %}
{% load threadedcommentstags %}

{% block head_title %}{% blocktrans %}Recipes{% endblocktrans %}{% endblock %}

{% block subnav %}

<div class="row">
<h5>Categories</h5>
<ul class="nav nav-pills nav-stacked">
<li class="active"><a href="#">All </a></li>
<li><a href="#">Breads</a></li>
<li><a href="#">Juice</a></li>
<li><a href="#">Desserts & Sweets</a></li>
<li><a href="#">Snacks</a></li>
<li><a href="#">Salad</a></li>
<li><a href="#">Sauce</a></li>
<li><a href="#">Soup</a></li>
</ul>
</div>
<div class="row">
<h5>Meal</h5>
<select name="meal" id="id_meal">
<option value="Any">Any</option>
<option value="Breakfast">Breakfast</option>
<option value="Lunch">Lunch</option>
<option value="Dinner">Dinner</option>
</select>
</div>
<div class="row">
<h5>Cuisine</h5>
<select name="cuisine" id="id_cuisine">
<option value="Any">Any</option>
<option value="African">African</option>
<option value="American">American</option>
<option value="Asian">Asian</option>
<option value="Austrian">Austrian</option>
<option value="Authentic">Authentic</option>
<option value="British">British</option>
<option value="Caribbean">Caribbean</option>
<option value="Chinese">Chinese</option>
<option value="Cuban">Cuban</option>
<option value="Eastern European">Eastern European</option>
<option value="French">French</option>
<option value="German">German</option>
<option value="Greek">Greek</option>
<option value="Hawaiian">Hawaiian</option>
<option value="Hungarian">Hungarian</option>
<option value="Andhra">Indian - Andhra</option>
<option value="Awadhi">Indian - Awadhi</option>
<option value="Bengali">Indian - Bengali</option>
<option value="Bihari">Indian - Bihari</option>
<option value="Goan">Indian - Goan</option>
<option value="Gujarati">Indian - Gujarati</option>
<option value="Hyderabadi">Indian - Hyderabadi</option>
<option value="Jain">Indian - Jain</option>
<option value="Kashmiri">Indian - Kashmiri</option>
<option value="Maharashtrian">Indian - Maharashtrian</option>
<option value="Parsi">Indian - Parsi</option>
<option value="Punjabi">Indian - Punjabi</option>
<option value="Rajasthani">Indian - Rajasthani</option>
<option value="Sindhi">Indian - Sindhi</option>
<option value="South Indian">Indian - South Indian</option>
<option value="Italian">Italian</option>
<option value="Japanese">Japanese</option>
<option value="Jewish">Jewish</option>
<option value="Korean">Korean</option>
<option value="Malaysian">Malaysian</option>
<option value="Mediterranean">Mediterranean</option>
<option value="Mexican">Mexican</option>
<option value="Middle Eastern">Middle Eastern</option>
<option value="Moroccan">Moroccan</option>
<option value="Pacific Northwest">Pacific Northwest</option>
<option value="Scandinavian">Scandinavian</option>
<option value="South American">South American</option>
<option value="Spanish">Spanish</option>
<option value="Swiss">Swiss</option>
<option value="Thai">Thai</option>
<option value="Vietnamese">Vietnamese</option>
</select>
</div>
<div class="row">
<h5>Cooking Method</h5>
<select name="cookingmethod" id="id_cookingmethod">
<option value="Any">Any</option>
<option value="Bake">Bake</option>
<option value="Blender">Blender</option>
<option value="Bread Machine">Bread Machine</option>
<option value="Broil">Broil</option>
<option value="Convection Oven">Convection Oven</option>
<option value="Fondue">Fondue</option>
<option value="Food Processor">Food Processor</option>
<option value="Fry">Fry</option>
<option value="Grill">Grill</option>
<option value="Grill Pan">Grill Pan</option>
<option value="Grind">Grind</option>
<option value="Ice-Cream Maker">Ice-Cream Maker</option>
<option value="Marinate">Marinate</option>
<option value="Microwave">Microwave</option>
<option value="Poach">Poach</option>
<option value="Pressure Cooker">Pressure Cooker</option>
<option value="Roast">Roast</option>
<option value="Microwave">Microwave</option>
<option value="Sandwich Press">Sandwich Press</option>
<option value="Slow Cook">Slow Cook</option>
<option value="Steam">Steam</option>
<option value="Waffle Maker">Waffle Maker</option>
</select>
                    
</div>

<div class="row">
   <a href="{% url upload_recipe %}" class="btn primary">Upload a Recipe</a>
 </div>

{%endblock%}


{% block body %}
    <div class="well" style="background:white;">
    <h4>Filters to do</h5>
    <select name="servings" id="id_servings">
<option value="One" selected="selected">One</option>
<option value="Two">Two</option>
<option value="Three">Three</option>
<option value="Four">Four</option>
<option value="Five">Five</option>
<option value="Six">Six</option>
<option value="Seven">Seven</option>
<option value="Eight">Eight</option>
<option value="Nine">Nine</option>
<option value="Ten">Ten</option>
</select>
    <!-- alternate -->
    {% if recipes %}
    
    {% autopaginate recipes 5 %}
        
        <table class="recipes">
            {% for recipe in recipes %}
                <tr class="{% cycle odd,even %}">
                    <!-- meta -->
              
                    <!-- recipe info -->
                    <td>
                        <h3><a href="/recipes/{{ recipe.id }}/recipe/">{{ recipe.name }}</a></h2>
                        <div class="body">
                            <strong><i>Also Known as :{{ recipe.alsoknownas }}<br />Category : {{ recipe.category }}<br /> Type : {{ recipe.recipetype }}</strong></i>
                        
                        </div>
                       
                       {% ifequal list 'yours' %}
                            <table>
                                <tr>
                                    <td>
                                        <!-- udpate recipe -->
                                        <form method="GET" action="{% url update_recipe recipe.id %}">
                                            <input type="submit" class="btn primary" value="{% trans "Update" %}" />
                                        </form>
                                    </td>
                                    <td>
                                        <!-- delete recipe -->
                                        <form method="POST" action="{% url delete_recipe recipe.id %}">
                                            <input type="submit" class="btn danger" value="{% trans "Delete" %}" />
                                        </form>
                                    </td>
                                </tr>
                            </table>
                        {% endifequal %}
                    </td>
                    <!-- recipe art -->
                    <td>
                        <div class="recipeart" >{{ recipe.thumbmedium|safe }}</div>
                    </td>
                </tr>
            {% endfor %}
        </table>
        
    {% paginate %}

    {% else %}
        <p>{% trans "No recipes yet." %}</p>
    {% endif %}
    </div>
{% endblock %}

apps/recipes/templates/recipes/recipes_base.html
{% extends "site_base.html" %}

{% load i18n %}

{% block body_base %}
     <div class="container">  
        <div class="row">
        <h3 style="color:green;margin-top:-25px;float:left;"><img src="{{ STATIC_URL }}icons/recipes.png"/> Recipes</h3>
           <a href="/restaurants" class="btn" style="margin-top:-25px;float:right;">Restaurants</a>
        <hr/>
        </div>
  
     <div class="row" >
            <div class="span3 columns">
                {% block subnav %}
                {% endblock %}
            </div>
             
              
            <div class="span11 columns" >
                {% block body %}
                {% endblock %}
            </div>
            <div class="span2 columns">
           <a href="{%url photos%}" class="btn success"><i class="icon-camera icon-white"></i>{% trans " Photos" %}</a> 
          </div>
        </div>
        
    </div>

     
{% endblock %}

apps/recipes/templates/recipes/smallimg.html
<div class="clearfix" style="text-align:center;">
                <div class="input">
                Change <input type="file" name="recipeart" id="id_recipearts" />
                 </div>
            
        </div>

apps/recipes/templates/recipes/update.html
{% extends "subnav_base.html" %}

{% load i18n %}

{% load bootstrap_tags %}


{% block head_title %}{% blocktrans %}Update Recipe{% endblocktrans %}{% endblock %}

{% block extra_head %}
<script>

     $(document).ready(function(){

   //script to correct Django ImageField bugs    
    $("#id_recipeart").parent().parent().remove();
   //end of ImageField

});
</script>
{% endblock %}
{% block subnav %}
   
<a href="/recipes/{{ recipe.id }}/recipe/"><div class="resart" >{{ recipe.thumbmedium|safe }}</div>
        <h4>{{ recipe.name }} </h4></a><br/>
   <div class="row">           
    <a href="#deleteModal" data-backdrop="true" data-keyboard="true" data-toggle="modal" class="btn danger" style="text-align:right;">Delete</a> 
</div>
{%endblock%}
{% block body %}

    {% if user == recipe.adder %}
    <h3 style="text-align:center;">{% trans "Update" %}</h3><hr/>
        <div class="well"><form enctype="multipart/form-data" method="POST" action="" class="uniForm">
           
            <fieldset class="inlineLabels">
                                 <h4 style="text-align:center;">Recipe Art</h4><hr/><div class="resart" style="text-align:center;" >{{ recipe.thumbmedium|safe }}</div> <br/>      
{%include "recipes/smallimg.html"%}
                  </div><div class="well" id="detailsdiv">
                 <h4 style="text-align:center;">Details</h4>  <hr/>
           <div style="text-align:center;" id="formdiv">      
        {{ recipe_form|as_bootstrap }}
       </div>         
       <div class="actions">
                    <input type="submit" class="btn primary" value="{% trans 'Update' %}">
                     <a href="/recipes/{{ recipe.id }}/recipe/" class="btn ">Cancel</a>      
          </div>
            </fieldset>
        </form>
      </div>
  
<div class="modal hide " id="deleteModal">
 <div class="modal-header">
    <a class="close" data-dismiss="modal" href="#">&times;</a>
    <h3>Delete {{recipe.name}}</h3>
  </div><br/>
  <div class="modal-body"> 	
  <p class="landingtext">Are you sure you want to delete?</p> 
  </div>
  <div class="modal-footer">
  
                              
                     <a href="{% url delete_recipe recipe.id %}" type="submit" class="btn danger"> <i class="icon-trash icon-white"></i>{% trans " Delete" %} </a>
                     <a href="#" class="btn" data-dismiss="modal" >Cancel</a>                          
  

    </div>

</div>    
</div> 

 {% endif %}
   
     


{% endblock %}